name: Build and package python apps

on:
  push:
    branches:
      main

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      PYTHONVERSION: "3.11.1"
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      PYI_BUILD_MODE: "onedir"

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python download
      id: cache-python-download
      uses: actions/cache@v3
      with:
        path: ~/python.pkg
        key: macOS-Python-${{ env.PYTHON_VERSION }}

    - name: Get Python
      run: |
       curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg

    - name: Install Python
      run: sudo installer -pkg ~/python.pkg -target /

    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip3 install --upgrade pip wheel
        pip3 install pyinstaller
        pyinstaller DIP.spec
      
    - name: Log files
      run: |
        ls dist
        ls dist/DIP
        mkdir DIP
        mv ./dist/DIP.app ./DIP/DIP.app
        hdiutil create -srcfolder ./DIP DIP.dmg

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        # repo_token: ${{ secrets.TOKEN }}
        file: DIP.dmg
        asset_name: DIP.dmg
        tag: latest-mac-build
        overwrite: true
        
  build-linux:
    runs-on: ubuntu-latest
    env:
      PYI_BUILD_MODE: "onedir"

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip3 install pyinstaller
        sudo apt install python3-tk python3-pil.imagetk

    - name: Build
      run: pyinstaller DIP.spec
      
    - name: Log files
      run: |
        ls dist
        ls dist/DIP
        cd dist; zip -0 -r -y DIP.zip DIP

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/DIP.zip
        asset_name: DIP.zip
        tag: latest-linux-build
        overwrite: true
  
  build-windows:
    runs-on: windows-latest
    env:
      PYI_BUILD_MODE: "onefile"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip install --upgrade pip wheel
        pip install pyinstaller
        pyinstaller DIP.spec
      
    - name: Log files
      run: |
        ls
        echo "_"
        ls dist -R

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/DIP.exe
        asset_name: DIP.exe
        tag: latest-windows-build
        overwrite: true
