name: Build and package Mac version

on:
  push:
    branches:
      main

jobs:
  build-app:
    name: Build for Mac
    runs-on: macos-latest
    env:
      PYTHONVERSION: "3.10.0"
      MACOSX_DEPLOYMENT_TARGET: "10.9"

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python download
      id: cache-python-download
      uses: actions/cache@v3
      with:
        path: ~/python.pkg
        key: macOS-Python-${{ env.PYTHON_VERSION }}

    - name: Get Python
      run: |
       curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg

    - name: Install Python
      run: sudo installer -pkg ~/python.pkg -target /

    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip3 install --upgrade pip wheel
        python3 pip install pyinstaller
        python3 -O -m pyinstaller DIP.spec
      
    - name: Log files
      run: |
        ls dist
        ls dist/DIP
        mkdir DIP
        mv ./dist/DIP.app ./DIP/DIP.app
        hdiutil create -srcfolder ./DIP DIP.dmg

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: DIP.dmg
        asset_name: DIP.dmg
        tag: latest-mac-build
        overwrite: true